services:
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

  express-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MINIO_ENDPOINT=localhost
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_DOCUMENTOS=documentos
      - BUCKET_TESIS=tesis
      - BUCKET_ACTAS=actas
      - BUCKET_CERTIFICADOS=certificados
      - BUCKET_AUTOCYBER=autocyber
      - BUCKET_METADATOS=metadatos
      - BUCKET_TURNITIN=turnitin
      - DEBUG=express:*
    command: npm run dev  # Usa Nodemon para iniciar la aplicación
    depends_on:
      - minio
    networks:
      - app-network

  vite-app:
    build:
      context: ./
      dockerfile: Dockerfile # Asegúrate de que este Dockerfile está en la raíz del proyecto
    ports:
      - "5173:5173"
    environment:
      VITE_PORT: 5173
    volumes:
      - ./:/app # Monta la raíz del proyecto en /app dentro del contenedor
      - /app/node_modules # Volumen anónimo
      #- node_modules:/app/node_modules # Crea un volumen anónimo para node_modules
    networks:
      - app-network

networks:
  app-network:

volumes:
  minio-data:
  #node_modules:
